// <auto-generated />
namespace VecturaServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Town : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Town));
        
        string IMigrationMetadata.Id
        {
            get { return "201803081738586_Town"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
